---
- name: creating folder to store installable
  file:
    path: "{{redhat_tmp_dir}}"
    state: directory
    recurse: yes

- name: copying installable to target server
  get_url:
    url: "{{sw_url}}/{{env}}_packages/{{vars[env].redhat.installable}}"
    dest: "{{redhat_tmp_dir}}"
    checksum: "{{vars[env].redhat.checksum}}"

- name: unzipping installable
  unarchive:
    src: "{{redhat_tmp_dir}}/{{vars[env].redhat.installable}}"
    dest: "{{redhat_tmp_dir}}"
    mode: 0755
    remote_src: yes 

- name: install McAfee agent on target server
  shell: "{{redhat_tmp_dir}}/install.sh -u"
  register: install_result
  changed_when: "'Agent Successfully Installed' in install_result.stdout"
  failed_when: "'Agent Successfully Installed' not in install_result.stdout and 'higher or same version of the agent is already installed' not in install_result.stdout and install_result.rc != 0"
  become: yes

- name: Start McAfee service
  service:
    name: cma
    state: started
    enabled: yes
  become: yes
